In [19]:
import pandas as pd
import numpy as np

In [20]:
# Read factor data in and get data for specified year
data = pd.read_csv('insample.csv')
# data = data.query("year==" + str(2009))

data.head()

,year,permno,INDUSTRY,ret1yr,ret1yrafter,PRC,SHROUT,TICKER_x,NCUSIP,HEXCD,...,exret,Tbi,OPA,Sp,IG,IK,Rds,Adm,dp,NS
0,1980,10006,37,0.430885,-0.055132,46.00,9009.0,ACF,80010,1,...,0.027725,1.523326,3.666592,0.002521,0.0,0.257261,1.584165e-05,0.000008,0.000052,0.0
1,1980,10057,35,0.032209,-0.120720,25.50,4273.0,AMT,462610,1,...,0.003191,1.647547,2.125341,0.003719,0.0,0.289211,3.348889e-05,0.000030,0.000054,0.0
2,1980,10065,67,0.424879,0.060158,16.25,16254.0,ADX,621210,1,...,-0.017337,3.024857,1.741851,0.002621,0.0,0.165874,2.665719e-05,0.000096,0.000049,0.0
3,1980,10137,49,0.002571,0.341439,13.75,40288.0,AYP,1741110,1,...,-0.023246,1.501683,2.267348,0.002093,0.0,0.109156,2.183479e-07,0.000039,0.000164,0.0
4,1980,10145,28,0.133302,-0.140999,53.50,33489.0,ACD,1908710,1,...,-0.031358,3.204152,4.000000,0.003080,0.0,0.445400,5.860482e-05,0.000090,0.000052,0.0

In [21]:
table = pd.pivot_table(data, values=['sale_invcap', 'roa', 'GProf'], index='year', columns='permno')
table

        GProf                                                             \
permno  10002  10006  10010  10012  10016  10017  10019     10020  10025
year
1980      NaN  0.251    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1981      NaN  0.239    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1982      NaN  0.243    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1983      NaN  0.169    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1984      NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1985      NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN
1986      NaN    NaN    NaN    NaN  0.411  0.496    NaN  0.084794    NaN
1987      NaN    NaN    NaN    NaN  0.411  0.528    NaN  0.041000    NaN
1988      NaN    NaN    NaN    NaN  0.415    NaN    NaN  0.040000    NaN
1989      NaN    NaN    NaN    NaN  0.131    NaN    NaN  0.043000    NaN
1990      NaN    NaN    NaN    NaN  0.365    NaN    NaN  0.043000    NaN
1991      NaN    NaN  0.658    NaN  0.319    NaN    NaN  0.045000    NaN
1992      NaN    NaN    NaN    NaN  0.296    NaN    NaN  0.049000    NaN
1993      NaN    NaN    NaN    NaN  0.292    NaN    NaN       NaN    NaN
1994      NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.526
1995      NaN    NaN    NaN  0.455  0.170    NaN    NaN       NaN  0.490
1996      NaN    NaN    NaN    NaN  0.269    NaN    NaN       NaN  0.113
1997    0.049    NaN    NaN    NaN  0.155    NaN  0.715       NaN  0.314
1998    0.058    NaN    NaN    NaN  0.214    NaN    NaN       NaN  0.321
1999      NaN    NaN    NaN  0.705  0.256    NaN    NaN       NaN  0.341
2000      NaN    NaN    NaN    NaN  0.341    NaN    NaN       NaN  0.330
2001      NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.350
2002      NaN    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.323
2003    0.044    NaN    NaN    NaN    NaN    NaN    NaN       NaN    NaN
2004    0.036    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.384
2005    0.042    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.493
2006    0.047    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.533
2007    0.039    NaN    NaN    NaN    NaN    NaN    NaN       NaN  0.519

               ... sale_invcap                                              \
permno  10026  ...       92815  92866  92874 93009  93060     93084  93105
year           ...
1980      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1981      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1982      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1983      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1984      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1985      NaN  ...         NaN    NaN    NaN   NaN    NaN  1.461500    NaN
1986      NaN  ...       1.451    NaN    NaN   NaN    NaN  1.342598    NaN
1987      NaN  ...         NaN    NaN    NaN   NaN    NaN  1.307547    NaN
1988      NaN  ...       1.858    NaN    NaN   NaN    NaN       NaN    NaN
1989    0.732  ...       1.722    NaN    NaN   NaN    NaN       NaN    NaN
1990      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1991    0.602  ...       1.819    NaN    NaN   NaN    NaN       NaN    NaN
1992      NaN  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1993    0.758  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN
1994    0.822  ...         NaN    NaN    NaN   NaN  1.721       NaN    NaN
1995      NaN  ...         NaN    NaN    NaN   NaN  1.063       NaN    NaN
1996    0.867  ...         NaN    NaN    NaN  5.32    NaN       NaN  0.492
1997    0.902  ...         NaN  1.241    NaN  6.50    NaN       NaN  0.642
1998    0.725  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.626
1999    0.818  ...         NaN  1.525    NaN   NaN    NaN       NaN  0.705
2000    0.868  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.736
2001    0.894  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.772
2002    0.680  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.658
2003    0.631  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.530
2004    0.591  ...         NaN    NaN  1.891   NaN    NaN       NaN  0.551
2005    0.585  ...         NaN    NaN  1.588   NaN    NaN       NaN  0.591
2006    0.577  ...         NaN    NaN    NaN   NaN    NaN       NaN  0.715
2007    0.560  ...         NaN    NaN    NaN   NaN    NaN       NaN    NaN


permno   93156  93201  93220
year
1980       NaN    NaN    NaN
1981       NaN    NaN    NaN
1982       NaN    NaN    NaN
1983       NaN    NaN    NaN
1984       NaN    NaN    NaN
1985       NaN  2.893    NaN
1986       NaN  2.740    NaN
1987       NaN  1.805  1.914
1988       NaN  1.942  2.129
1989    11.126  1.565  2.290
1990    13.032    NaN    NaN
1991       NaN    NaN    NaN
1992       NaN    NaN    NaN
1993       NaN    NaN    NaN
1994       NaN    NaN    NaN
1995       NaN    NaN    NaN
1996       NaN    NaN    NaN
1997       NaN    NaN    NaN
1998       NaN    NaN    NaN
1999       NaN    NaN    NaN
2000       NaN    NaN    NaN
2001       NaN    NaN    NaN
2002       NaN    NaN    NaN
2003       NaN    NaN    NaN
2004       NaN    NaN    NaN
2005       NaN    NaN    NaN
2006       NaN    NaN    NaN
2007       NaN    NaN    NaN

[28 rows x 33573 columns]

In [22]:
# Is mean value because pivot_table took mean over the year as default aggregation function?
applied = table.apply(lambda x: x / x.shift(1)) # This year's mean value over last year's value

In [23]:
test = applied.loc[2007, (slice(None), 10002)]
test

             permno
GProf        10002     0.829787
roa          10002     0.692308
sale_invcap  10002     1.169451
Name: 2007, dtype: float64

In [24]:

weights = {
    'GProf': 1.9,
    'roa': 0.3,
    'sale_invcap': 1.4,
}
results = {}
score = 0
x = 0
vals = test.values
why_not = []
fund_mom = np.array([])
def fund_mom_score(year: int, permno: int, weights: dict):
    """Takes a year, permno, and dict with weights for each fundamental factor, then computes a 
    fundamental momentum score representing a combination of the year to year trend in those fundamental factors
    for that specific ticker for the specific year.
    """
    year_ticker_slice = applied.loc[year, (slice(None), permno)]
    vals = year_ticker_slice.values
    score = 0
    for i, factor in enumerate(year_ticker_slice.keys()):
        results[factor[0]] = vals[i]
    for key in results.keys():
        score = score + (weights[key] * results[key])
    return score
for year, permno in zip(data['year'].values, data['permno'].values):
    f_score = fund_mom_score(year, permno, weights)
    np.append(fund_mom, f_score)
    why_not.append(f_score)
#     print(fund_mom_score(year,permno,weights))
    
# np.append(fund_mom, fund_mom_score(2007, 10002, weights))

# Idea, combine these values into one "general fundamental momentum" value
# Each company should have a fund_mom value for that year
# i.e. each permno should get a fund_mom value added
# We're adding a fund_mom column

C:\Users\erueb\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: RuntimeWarning: invalid value encountered in double_scalars

In [25]:
fund_mom

array([], dtype=float64)

In [26]:
len(why_not)

82695

In [27]:
data['fund_mom'] = pd.Series(why_not)

In [28]:
data.shape

(82695, 102)

In [29]:
data.to_csv('./in_sample_w_fund_mom.csv')

In [30]:
# Read factor data in and get data for specified year
data = pd.read_csv('outofsample1.csv')
# data = data.query("year==" + str(2009))

data.head()

,year,permno,INDUSTRY,ret1yr,ret1yrafter,PRC,SHROUT,TICKER_x,NCUSIP,HEXCD,...,exret,Tbi,OPA,Sp,IG,IK,Rds,Adm,dp,NS
0,2008,10002,60,0.282612,-0.804133,14.76,17555.0,BTFG,05978R10,3,...,0.140503,0.765127,0.230999,0.000498,-0.164989,0.099520,6.991679e-06,0.000002,0.000036,0.450396
1,2008,10025,30,-0.450797,1.177474,17.58,6750.0,AEPI,00103110,3,...,-0.145273,-0.426495,7.290761,0.006423,-0.572116,0.118046,9.269793e-06,0.000120,0.000000,-0.140840
2,2008,10026,20,0.161103,0.125422,35.88,18322.0,JJSF,46603210,3,...,0.180336,1.644152,2.495557,0.000957,0.153301,0.244202,8.685819e-07,0.000003,0.000011,0.012591
3,2008,10032,36,-0.354531,0.680234,16.95,39327.0,PLXS,72913210,3,...,-0.016206,1.219517,0.707167,0.002763,0.372064,0.299887,9.491621e-05,0.000012,0.000000,0.003995
4,2008,10051,38,0.317895,-0.046864,14.51,30799.0,HGR,41043F20,1,...,-0.166142,1.661594,3.666949,0.001573,0.569268,0.425434,6.317714e-05,0.000023,0.000013,0.088434

In [31]:
table = pd.pivot_table(data, values=['sale_invcap', 'roa', 'GProf'], index='year', columns='permno')
table

        GProf                                                             \
permno  10002  10025  10026  10032  10051     10065  10104  10107  10116
year
2008    0.034  0.283  0.523  0.237  0.467  0.064200  0.439  0.756  0.465
2009      NaN  0.498  0.537  0.185  0.210  0.051288  0.394  0.636 -0.218
2010      NaN  0.373  0.531  0.189  0.131  0.069927  0.380  0.647    NaN
2011      NaN  0.362  0.471  0.201  0.136  0.062633  0.405  0.566    NaN
2012      NaN  0.476  0.466  0.191  0.141  0.063364  0.394  0.485    NaN

               ... sale_invcap                                               \
permno  10137  ...       93419  93420  93422  93423  93426     93427  93428
year           ...
2008    0.116  ...         NaN    NaN    NaN    NaN    NaN       NaN    NaN
2009    0.093  ...         NaN    NaN    NaN    NaN    NaN       NaN    NaN
2010    0.111  ...    0.564727  0.260  0.530  0.669  1.243  1.215124  4.112
2011      NaN  ...    0.806062  0.298  0.610  0.454  1.210  1.246434  1.036
2012      NaN  ...    0.417593  0.370  0.454  0.503  1.114  1.177993  0.707


permno  93433  93435  93436
year
2008      NaN    NaN    NaN
2009      NaN    NaN    NaN
2010    0.767  3.778  0.844
2011      NaN    NaN  0.518
2012      NaN    NaN  0.317

[5 rows x 12309 columns]

In [36]:
# Is mean value because pivot_table took mean over the year as default aggregation function?
applied = table.apply(lambda x: x / x.shift(1)) # This year's mean value over last year's value
applied

       GProf                                                              \
permno 10002     10025     10026     10032     10051     10065     10104
year
2008     NaN       NaN       NaN       NaN       NaN       NaN       NaN
2009     NaN  1.759717  1.026769  0.780591  0.449679  0.798881  0.897494
2010     NaN  0.748996  0.988827  1.021622  0.623810  1.363420  0.964467
2011     NaN  0.970509  0.887006  1.063492  1.038168  0.895683  1.065789
2012     NaN  1.314917  0.989384  0.950249  1.036765  1.011671  0.972840

                                      ... sale_invcap                      \
permno     10107     10116     10137  ...       93419     93420     93422
year                                  ...
2008         NaN       NaN       NaN  ...         NaN       NaN       NaN
2009    0.841270 -0.468817  0.801724  ...         NaN       NaN       NaN
2010    1.017296       NaN  1.193548  ...         NaN       NaN       NaN
2011    0.874807       NaN       NaN  ...    1.427348  1.146154  1.150943
2012    0.856890       NaN       NaN  ...    0.518065  1.241611  0.744262


permno     93423     93426     93427     93428 93433 93435     93436
year
2008         NaN       NaN       NaN       NaN   NaN   NaN       NaN
2009         NaN       NaN       NaN       NaN   NaN   NaN       NaN
2010         NaN       NaN       NaN       NaN   NaN   NaN       NaN
2011    0.678625  0.973451  1.025767  0.251946   NaN   NaN  0.613744
2012    1.107930  0.920661  0.945091  0.682432   NaN   NaN  0.611969

[5 rows x 12309 columns]

In [33]:

weights = {
    'GProf': 1.9,
    'roa': 0.3,
    'sale_invcap': 1.4,
}
results = {}
score = 0
x = 0
vals = test.values
why_not = []
fund_mom = np.array([])
def fund_mom_score(year: int, permno: int, weights: dict):
    """Takes a year, permno, and dict with weights for each fundamental factor, then computes a 
    fundamental momentum score representing a combination of the year to year trend in those fundamental factors
    for that specific ticker for the specific year.
    """
    year_ticker_slice = applied.loc[year, (slice(None), permno)]
    vals = year_ticker_slice.values
    score = 0
    for i, factor in enumerate(year_ticker_slice.keys()):
        results[factor[0]] = vals[i]
    for key in results.keys():
        score = score + (weights[key] * results[key])
    return score
for year, permno in zip(data['year'].values, data['permno'].values):
    f_score = fund_mom_score(year, permno, weights)
    np.append(fund_mom, f_score)
    why_not.append(f_score)
#     print(fund_mom_score(year,permno,weights))
    
# np.append(fund_mom, fund_mom_score(2007, 10002, weights))

# Idea, combine these values into one "general fundamental momentum" value
# Each company should have a fund_mom value for that year
# i.e. each permno should get a fund_mom value added
# We're adding a fund_mom column

In [34]:
data['fund_mom'] = pd.Series(why_not)

In [35]:
data.to_csv('./oos_w_fund_mom.csv')

In [ ]:
def